### PR TITLE
Basic version of snabb application

### PR DESCRIPTION
**Pull request by cryslith**
Basic working version of the snabb side of spike with both the controller and the NIC stubbed out.

### CODE REVIEW

**Comment by ed1d1a8d** [comment]
Has there been any progress in terms of Go-Lua integration?

**Comment by cryslith** [comment]
Should be easy, I just haven't done it yet.  I have tested having snabb apps call C code, and having C code call go code, so there shouldn't be any problem.

**Comment by ed1d1a8d** [comment]
Could you expand a bit on how the Snabb-C and C-Go steps work?

**Comment by cryslith** [comment]
Well, they're really the same "step" as we'll be communicating directly from snabb to Go via the cdecl interface.  (So we aren't actually writing any C code.)  We compile the Go part as a dynamic-linked library (see [here](https://docs.google.com/document/d/1nr-TQHw_er6GOQRsF6T43GGhFDelrAP0NqSS_00RgZQ/edit#heading=h.1gw5ytjfcoke) for the docs on this process), and then load the resulting object and call into it from our snabb application.

**Comment by ed1d1a8d** [comment]
I see, thanks for the clarification.

**Pull request merged**
